//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCShoesShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEU_GIAO_HANG
    {
        public int MaPGH { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PHIEU_GIAO_HANG PHIEU_GIAO_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
