//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCShoesShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANG_NHAP
    {
        public string id { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string PhanQuyen { get; set; }
    }
}
