//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCShoesShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_GIAO_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_GIAO_HANG()
        {
            this.CT_PHIEU_GIAO_HANG = new HashSet<CT_PHIEU_GIAO_HANG>();
        }
    
        public int MaPGH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_GIAO_HANG> CT_PHIEU_GIAO_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
